stackcADTlient: stackADTclient.o stackADT.o
	gcc -o stackADTclient.out stackADTclient.o stackADT.o

stackADTclient.o: stackADTclient.c stackADT.h
	gcc -c stackADTclient.c

stackADT.o: stackADT.c stackADT.h
	gcc -c stackADT.c
